### ISSUE TITLE
Fresh CLI install failed

### ISSUE THREAD

**Issue by no1melman** [Microsoft/service-fabric-cli#109]
I'm following this:

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cli#install-pip-python-and-the-service-fabric-cli

I got python installed ran versions check, then tried to install sfctl:

> C:\WINDOWS\system32> python --version
> Python 3.7.0
> C:\WINDOWS\system32> pip --version
> pip 10.0.1 from c:\users\melman\appdata\local\programs\python\python37\lib\site-packages\pip (python 3.7)
> C:\WINDOWS\system32> pip install sfctl
> Collecting sfctl
>   Could not find a version that satisfies the requirement sfctl (from versions: )
> No matching distribution found for sfctl

**Comment by Christina-Kang** [comment]
It seems that there is some issue with python 3.7. Can you try python 3.6 as a mitigation? If that doesn't work, please let me know. Thanks!

**Comment by no1melman** [comment]
Oh okay, I will give that a try tonight thanks.
