### ISSUE TITLE
sfctl property put doesn't register value

### ISSUE THREAD

**Issue by gustafcarleson** [Microsoft/service-fabric-cli#153]
Hi

I'm trying to use sfctl to set a property. It registers but the value is null. Why?

using sfctl:

`sfctl property put --name-id "MyApp" --property-name "fun.property" --value "{\"Kind\": \"String\", \"Data\": \"asdf\"}"`

Result:

```
{

  "additionalProperties": {},
  "continuationToken": "",
  "isConsistent": true,
  "properties": [
    {
      "additionalProperties": {},
      "metadata": {
        "additionalProperties": {},
        "customTypeId": "",
        "lastModifiedUtcTimestamp": "2018-11-09T10:21:46.197000+00:00",
        "parent": "fabric:/MyApp",
        "sequenceNumber": "882",
        "sizeInBytes": 10,
        "typeId": "String"
      },
      "name": "fun.property",
      "value": null    <-------------
    }
  ]
}
```

-----------

sfctl version: 6.0.0
cluster runtime version: 6.3.187.9494
cluster location: Azure
log:

Command arguments: ['property', '--verbose', 'put', '--name-id', 'MyApp', '--property-name', 'fun.property', '--value', '{"Kind": "String","Data": "somevalue"}', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function on_global_arguments at 0x0000000002FB10B8>, <function on_global_arguments at 0x0000000002FCB588>, <function on_global_arguments at 0x0000000002FE3828>]
Event: CommandInvoker.OnPreCommandTableCreate [<function remove_logger_flags at 0x0000000002FB1128>]
Event: CommandLoader.OnLoadArguments []
Event: CommandInvoker.OnPostCommandTableCreate []
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs []
Event: CommandInvoker.OnPostParseArgs [<function handle_output_argument at 0x0000000002FCB5F8>, <function handle_query_parameter at 0x0000000002FE3898>]
msrest.service_client : Accept header absent and forced to application/json
msrest.pipeline : Configuring request: timeout=100, verify=True, cert=None
msrest.pipeline : Configuring proxies: ''
msrest.pipeline : Evaluate proxies against ENV settings: True
msrest.pipeline : Configuring redirects: allow=True, max=30
msrest.pipeline : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
urllib3.connectionpool : Starting new HTTPS connection (1): ...cloudapp.azure.com:19080
c:\program files\python27\lib\site-packages\urllib3\connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
urllib3.connectionpool : https://...cloudapp.azure.com:19080 "PUT /Names/MyApp/$/GetProperty?api-version=6.0&timeout=60 HTTP/1.1" 200 0
Event: CommandInvoker.OnTransformResult []
Event: CommandInvoker.OnFilterResult []
Event: Cli.PostExecute []

**Comment by Christina-Kang** [comment]
@gustafcarleson Thank you for reporting this! It seems like a possible bug on our end. I will investigate and follow up on this thread soon. Sorry for the inconvenience.

**Comment by gustafcarleson** [comment]
How embarrassing, yes, I omitted the include values option. Thank you.

**Comment by Christina-Kang** [comment]
Glad it's working! Closing the issue.
