### ISSUE TITLE
sfctl application upload completes but app not visible

### ISSUE THREAD

**Issue by IsaackRasmussen** [Microsoft/service-fabric-cli#154]
sfctl version 6.0.0
Cluster: 6.3.187.9494
Hosted: On premise, Windows server 2016

I'm trying to install Traefik on my cluster but when executing the upload: 
 sfctl application upload --path Traefik/ApplicationPackageRoot --show-progress --debug
It appears to complete just fine but it never shows up in Service Fabric Explorer.

How do I diagnose further as to what went wrong?

-- Debug output
Command arguments: ['application', 'upload', '--path', 'Traefik/ApplicationPackageRoot', '--show-progress', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x1017597b8>, <function OutputProducer.on_global_arguments at 0x1017c8378>, <function CLIQuery.on_global_arguments at 0x1017ead90>]
Event: CommandInvoker.OnPreCommandTableCreate [<function CLILogging.remove_logger_flags at 0x101759840>]
Event: CommandLoader.OnLoadArguments []
Event: CommandInvoker.OnPostCommandTableCreate []
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs []
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x1017c8400>, <function CLIQuery.handle_query_parameter at 0x1017eae18>]
urllib3.connectionpool : Starting new HTTP connection (1): 10.0.15.83:19080
urllib3.connectionpool : http://10.0.15.83:19080 "PUT /ImageStore/ApplicationPackageRoot/ApplicationManifest.xml?api-version=6.1 HTTP/1.1" 200 0
[1/16] files, ApplicationManifest.xml
urllib3.connectionpool : http://10.0.15.83:19080 "PUT /ImageStore/ApplicationPackageRoot/.DS_Store?api-version=6.1 HTTP/1.1" 200 0
[2/16] files, .DS_Store
urllib3.connectionpool : http://10.0.15.83:19080 "PUT /ImageStore/ApplicationPackageRoot/_.dir?api-version=6.1 HTTP/1.1" 200 0
[3/16] files, _.dir
urllib3.connectionpool : http://10.0.15.83:19080 "PUT /ImageStore/ApplicationPackageRoot/Watchdog/ServiceManifest.xml?api-version=6.1 HTTP/1.1" 200 0
[4/16] files, Watchdog/ServiceManifest.xml
urllib3.connectionpool : http://10.0.15.83:19080 "PUT /ImageStore/ApplicationPackageRoot/Watchdog/_.dir?api-version=6.1 HTTP/1.1" 200 0
[5/16] files, Watchdog/_.dir
urllib3.connectionpool : http://10.0.15.83:19080 "PUT /ImageStore/ApplicationPackageRoot/Watchdog/Code/.gitignore?api-version=6.1 HTTP/1.1" 200 0
[6/16] files, Watchdog/Code/.gitignore
urllib3.connectionpool : http://10.0.15.83:19080 "PUT /ImageStore/ApplicationPackageRoot/Watchdog/Code/_.dir?api-version=6.1 HTTP/1.1" 200 0
[7/16] files, Watchdog/Code/_.dir
urllib3.connectionpool : http://10.0.15.83:19080 "PUT /ImageStore/ApplicationPackageRoot/TraefikPkg/.DS_Store?api-version=6.1 HTTP/1.1" 200 0
[8/16] files, TraefikPkg/.DS_Store
urllib3.connectionpool : http://10.0.15.83:19080 "PUT /ImageStore/ApplicationPackageRoot/TraefikPkg/ServiceManifest.xml?api-version=6.1 HTTP/1.1" 200 0
[9/16] files, TraefikPkg/ServiceManifest.xml
urllib3.connectionpool : http://10.0.15.83:19080 "PUT /ImageStore/ApplicationPackageRoot/TraefikPkg/_.dir?api-version=6.1 HTTP/1.1" 200 0
[10/16] files, TraefikPkg/_.dir
urllib3.connectionpool : http://10.0.15.83:19080 "PUT /ImageStore/ApplicationPackageRoot/TraefikPkg/Config/Settings.xml?api-version=6.1 HTTP/1.1" 200 0
[11/16] files, TraefikPkg/Config/Settings.xml
urllib3.connectionpool : http://10.0.15.83:19080 "PUT /ImageStore/ApplicationPackageRoot/TraefikPkg/Config/_.dir?api-version=6.1 HTTP/1.1" 200 0
[12/16] files, TraefikPkg/Config/_.dir
urllib3.connectionpool : http://10.0.15.83:19080 "PUT /ImageStore/ApplicationPackageRoot/TraefikPkg/Code/.DS_Store?api-version=6.1 HTTP/1.1" 200 0

**Comment by Christina-Kang** [comment]
`sfctl application upload` puts it in the image store only, and does not actually provision the application type, which is why you won't see it in Service Fabric Explorer. You can try provisioning the application type first, and only checking that the upload is correct if you hit an error and rule out mistakes in the app package. The upload step does not do any validation, so if provisioning fails, the most likely reason is that there is something wrong with the app package, rather than a failure in upload.

You can check that the upload is correct either by going to the image store service primary node, or by running `sfctl root-info` or `sfctl stat`. 

You can see this link for more details:
https://docs.microsoft.com/azure/service-fabric/service-fabric-application-lifecycle#deploy

The provision command is `sfctl application provision`.

**Comment by Christina-Kang** [comment]
@IsaackRasmussen I am closing this issue. Please let me know and reopen the issue if provisioning does not work. Thanks!
