### ISSUE TITLE
Update knack

### ISSUE THREAD

**Issue by Christina-Kang** [microsoft/service-fabric-cli#180]
Update to the latest (v6.0+) when it comes out

**Comment by Christina-Kang** [comment]
Same with sfmergeutil

**Comment by JamieMagee** [comment]
@Christina-Kang knack version 0.6.3 is currently out. Are there still plans to do this upgrade?

**Comment by Christina-Kang** [comment]
@JamieMagee yes we will be upgrading. Is there something specific you're looking for?

**Comment by JamieMagee** [comment]
Nothing specific, just wanted to know if this work was still planned. Knack 0.6.x has been out for a while and this issue is quite old.

**Comment by Christina-Kang** [comment]
@JamieMagee we've updated to version 0.6.3. It will be out with the next release :)

**Comment by Christina-Kang** [comment]
sfmergeutil is already at latest. No work to be done there.
