### ISSUE TITLE
Add a -v switch to display version of sfctl

### ISSUE THREAD

**Issue by sridmad** [Microsoft/service-fabric-cli#26]
or -h switch includes version information.

Helps with analyzing and reporting issues

**Comment by samedder** [comment]
Will consider it. As a workaround another option is to use pip: `pip show sfctl`

**Comment by mani-ramaswamy** [comment]
pip show sfctl gives me a blank.  Since this is now GA, we should have the versioning show up. with a --version switch.

**Comment by samedder** [comment]
@mani-ramaswamy do you have `pip` or `pip3`? Try `pip3 show sfctl`.

**Comment by Christina-Kang** [comment]
PR #104 adds this functionality. Use `sfctl -v` or `sfctl --version` for output on sfctl version, python version, OS, and python location.
