### ISSUE TITLE
New naming convention results in errors

### ISSUE THREAD

**Issue by samedder** [Microsoft/service-fabric-cli#36]
Whenever trying to pass an application or service id using the new convention of delimiting name sections with `~`, the operation fails with `FABRIC_E_INVALID_NAME_URI`.

For example `sfctl application info --application-id TestEd~Test` fails.

As a workaround however ` sfctl application info --application-id TestEd/Test` does work

**Comment by pouladpld** [comment]
I experienced the same problem using the latest version (supporting 6.0 runtime).

**Comment by Christina-Kang** [comment]
Issue has been fixed. Thanks!
