### ISSUE TITLE
please add a option to show the current connected cluster

### ISSUE THREAD

**Issue by qx-will** [Microsoft/service-fabric-cli#54]
I wish there is a option when invoke sfctl cluster to check what is the current connected cluster? i made several mistake to deploy the app onto the wrong cluster, after several times then before each deployment, i like to check which cluster i am actually connect to..

**Comment by samedder** [comment]
Thanks for the suggestion. This is a good first new feature that someone can add if they want to get familiar with the codebase.

**Comment by qx-will** [comment]
just make a PR to support this. @samedder

**Comment by Christina-Kang** [comment]
The command `sfctl cluster show-connection` has been added to display the connection string. Nothing is returned if no connection endpoint is found. Thanks!
